name: 'Compute Matrix Action'
description: 'Computes matrix'
inputs:
  BUILD_TYPE:
    description: 'The build type'
    required: true
outputs:
  MATRIX: 
    description: "Computed matrix"
    value: ${{ steps.compute-matrix.outputs.MATRIX }}
runs:
  using: "composite"
  steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Compute matrix
      id: compute-matrix
      run: |
        export PR_NUM="${GITHUB_REF_NAME##*/}"
        export BUILD_TYPE=${{ inputs.BUILD_TYPE }}
        MATRIX=$(ci/compute-mx.sh)
        echo "MATRIX=${MATRIX}" | tee -a ${GITHUB_OUTPUT}
      shell: bash
