# syntax=docker/dockerfile:1
FROM nvcr.io/nvidia/l4t-cuda:11.4.14-runtime

# originally written by Jason Tichy

ENV CUDA_VERSION 11.8
ENV APT_KEY_DONT_WARN_ON_DANGEROUS_USAGE=DontWarn

RUN rm /etc/apt/sources.list.d/* && \
    apt-get update && apt-get install -y gnupg2 ca-certificates


RUN wget -qq https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2004/arm64/cuda-ubuntu2004.pin && \
    mv cuda-ubuntu2004.pin /etc/apt/preferences.d/cuda-repository-pin-600 && \
    wget -qq https://developer.download.nvidia.com/compute/cuda/11.8.0/local_installers/cuda-tegra-repo-ubuntu2004-11-8-local_11.8.0-1_arm64.deb && \
    dpkg -i cuda-tegra-repo-ubuntu2004-11-8-local_11.8.0-1_arm64.deb && \
    cp /var/cuda-tegra-repo-ubuntu2004-11-8-local/cuda-*-keyring.gpg /usr/share/keyrings/ && \
    rm cuda-*
    
RUN apt-get update && \
    apt-get -y install \
            # base container
            cuda-cudart-$CUDA_VERSION \
            libglvnd-dev \
            # runtime container
            cuda-libraries-$CUDA_VERSION \
		        cuda-nvtx-$CUDA_VERSION \
            libcudnn8 \
            # devel container
            cuda-libraries-dev-$CUDA_VERSION \
		        cuda-nvml-dev-$CUDA_VERSION \
		        cuda-minimal-build-$CUDA_VERSION \
		        cuda-command-line-tools-$CUDA_VERSION \
		        libcudnn8-dev \
            && rm -rf /var/lib/apt/lists/*

            
            
RUN ln -s /usr/local/cuda-$CUDA_VERSION /usr/local/cuda
ENV PATH /usr/local/cuda/bin${PATH:+:${PATH}}
ENV LD_LIBRARY_PATH /usr/local/cuda/lib64:/usr/lib/aarch64-linux-gnu/tegra${LD_LIBRARY_PATH:+:${LD_LIBRARY_PATH}}

ENV NVIDIA_VISIBLE_DEVICES all
ENV NVIDIA_DRIVER_CAPABILITIES compute,utility
ENV NVIDIA_REQUIRE_CUDA "cuda>=11"
