name: Build and push image variant

on:
  workflow_call:
    inputs:
      ARCHES:
        required: true
        type: string
      CUDA_VER:
        required: true
        type: string
      LINUX_VER:
        required: true
        type: string
      PYTHON_VER:
        required: true
        type: string
      IMAGE_REPO:
        required: true
        type: string
      BUILD_TYPE:
        required: true
        type: string
      FULL_PREFIX:
        required: true
        type: string

jobs:
  docker-build:
    strategy:
      matrix:
        ARCH: ${{ fromJSON(inputs.ARCHES) }}
        CUDA_VER: ["${{ inputs.CUDA_VER }}"]
        LINUX_VER: ["${{ inputs.LINUX_VER }}"]
        PYTHON_VER: ["${{ inputs.PYTHON_VER }}"]
        FULL_PREFIX: ["${{ inputs.FULL_PREFIX }}"]
      fail-fast: false
    runs-on: "linux-${{ matrix.ARCH }}-cpu4"
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.GPUCIBOT_DOCKERHUB_USER }}
          password: ${{ secrets.GPUCIBOT_DOCKERHUB_TOKEN }}
      - name: Set up Docker Context for Buildx
        id: buildx-context
        run: |
          docker context create builders
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          driver: docker
          endpoint: builders
      - name: Get Real Arch and Manylinux Version
        id: get-real-arch
        run: |
          REAL_ARCH=$(arch)
          echo "REAL_ARCH=${REAL_ARCH}" >> $GITHUB_OUTPUT
          if [[ "${{ inputs.LINUX_VER }}" == "ubuntu20.04" || "${{ inputs.LINUX_VER }}" == "ubuntu18.04" ]]; then
            echo "MANYLINUX_VER=manylinux_2_31" >> $GITHUB_OUTPUT
          else
            echo "MANYLINUX_VER=manylinux_2_17" >> $GITHUB_OUTPUT
          fi
      - name: Build image
        if: 
        uses: docker/build-push-action@v4
        with:
          context: ./${{ inputs.IMAGE_REPO }}
          file: ./${{ inputs.IMAGE_REPO }}/Dockerfile
          push: true
          pull: true
          build-args: |
            CUDA_VER=${{ inputs.CUDA_VER }}
            LINUX_VER=${{ inputs.LINUX_VER }}
            PYTHON_VER=${{ inputs.PYTHON_VER }}
            CPU_ARCH=${{ matrix.ARCH }}
            REAL_ARCH=${{ steps.get-real-arch.outputs.REAL_ARCH }}
            MANYLINUX_VER=${{ steps.get-real-arch.outputs.MANYLINUX_VER }}
          tags: ${{ matrix.FULL_PREFIX }}cuda${{ matrix.CUDA_VER }}-${{ matrix.LINUX_VER }}-py${{ matrix.PYTHON_VER }}-${{ matrix.ARCH }}
