name: PR CI for citestwheel

on:
  pull_request:
    paths:
      - 'citestwheel/**'
      - '.github/workflows/prs-citestwheel.yml'

concurrency:
  group: "${{ github.workflow }}-${{ github.ref }}"
  cancel-in-progress: true

jobs:
  # arm64 tests run on ubuntu20.04 due to being built on ubuntu20.04 i.e. manylinux_2_31
  citestwheel-arm64-ctk118:
    uses: rapidsai/shared-action-workflows/.github/workflows/docker-buildx-native-multiarch.yml@feat/docker-buildx-multiarch
    secrets: inherit
    with:
      push: true
      docker-tag-multi: "rapidsai/citestwheel:cuda-devel-11.8.0-ubuntu20.04"
      docker-tag-arm64: "rapidsai/citestwheel:cuda-devel-11.8.0-ubuntu20.04-arm64"
      docker-build-arm64: "docker build --build-arg CPU_ARCH=arm64 --build-arg BASE_IMAGE=nvidia/cuda:11.8.0-devel-ubuntu20.04 --pull ./citestwheel -t rapidsai/citestwheel:cuda-devel-11.8.0-ubuntu20.04-arm64"
  citestwheel-arm64-ctk12:
    uses: rapidsai/shared-action-workflows/.github/workflows/docker-buildx-native-multiarch.yml@feat/docker-buildx-multiarch
    secrets: inherit
    with:
      push: true
      docker-tag-multi: "rapidsai/citestwheel:cuda-devel-12.0.0-ubuntu20.04"
      docker-tag-arm64: "rapidsai/citestwheel:cuda-devel-12.0.0-ubuntu20.04-arm64"
      docker-build-arm64: "docker build --build-arg CPU_ARCH=arm64 --build-arg BASE_IMAGE=nvidia/cuda:12.0.0-devel-ubuntu20.04 --pull ./citestwheel -t rapidsai/citestwheel:cuda-devel-12.0.0-ubuntu20.04-arm64"

  # amd64 tests run on ubuntu18.04 to ensure old OS support
  citestwheel-amd64-ctk118:
    uses: rapidsai/shared-action-workflows/.github/workflows/docker-buildx-native-multiarch.yml@feat/docker-buildx-multiarch
    secrets: inherit
    with:
      push: true
      docker-tag-multi: "rapidsai/citestwheel:cuda-devel-11.8.0-ubuntu18.04"
      docker-tag-amd64: "rapidsai/citestwheel:cuda-devel-11.8.0-ubuntu18.04-amd64"
      docker-build-amd64: "docker build --build-arg CPU_ARCH=amd64 --build-arg BASE_IMAGE=nvidia/cuda:11.8.0-devel-ubuntu18.04 --pull ./citestwheel -t rapidsai/citestwheel:cuda-devel-11.8.0-ubuntu18.04-amd64"
  citestwheel-amd64-ctk12:
    uses: rapidsai/shared-action-workflows/.github/workflows/docker-buildx-native-multiarch.yml@feat/docker-buildx-multiarch
    secrets: inherit
    with:
      push: true
      docker-tag-multi: "rapidsai/citestwheel:cuda-devel-12.0.0-ubuntu18.04"
      docker-tag-amd64: "rapidsai/citestwheel:cuda-devel-12.0.0-ubuntu18.04-amd64"
      docker-build-amd64: "docker build --build-arg CPU_ARCH=amd64 --build-arg BASE_IMAGE=nvidia/cuda:12.0.0-devel-ubuntu18.04 --pull ./citestwheel -t rapidsai/citestwheel:cuda-devel-12.0.0-ubuntu18.04-amd64"
