name: PR CI for manylinux

on:
  pull_request:
    paths:
      - 'manylinux/**'
      - '.github/workflows/prs-manylinux.yml'

concurrency:
  group: "${{ github.workflow }}-${{ github.ref }}"
  cancel-in-progress: true

jobs:
  # amd64 builds on centos7
  manylinux2014-amd64-ctk118:
    uses: rapidsai/shared-action-workflows/.github/workflows/docker-buildx-native-multiarch.yml@feat/docker-buildx-multiarch
    secrets: inherit
    with:
      push: true
      submodules: 'recursive'
      workdir: "./manylinux"
      docker-tag-multi: "rapidsai/manylinux2014:cuda-devel-11.8.0-centos7"
      docker-tag-amd64: "rapidsai/manylinux2014:cuda-devel-11.8.0-centos7-amd64"
      docker-build-amd64: "COMMIT_SHA=latest POLICY=manylinux2014 PLATFORM=x86_64 BASEIMAGE_OVERRIDE=nvidia/cuda:11.8.0-devel-centos7 ./build.sh && docker tag quay.io/pypa/manylinux2014_x86_64 rapidsai/manylinux2014:cuda-devel-11.8.0-centos7-amd64"
  manylinux2014-amd64-ctk120:
    uses: rapidsai/shared-action-workflows/.github/workflows/docker-buildx-native-multiarch.yml@feat/docker-buildx-multiarch
    secrets: inherit
    with:
      push: true
      submodules: 'recursive'
      workdir: "./manylinux"
      docker-tag-multi: "rapidsai/manylinux2014:cuda-devel-12.0.0-centos7"
      docker-tag-amd64: "rapidsai/manylinux2014:cuda-devel-12.0.0-centos7-amd64"
      docker-build-amd64: "COMMIT_SHA=latest POLICY=manylinux2014 PLATFORM=x86_64 BASEIMAGE_OVERRIDE=nvidia/cuda:12.0.0-devel-centos7 ./build.sh && docker tag quay.io/pypa/manylinux2014_x86_64 rapidsai/manylinux2014:cuda-devel-12.0.0-centos7-amd64"

  # arm64 builds on ubuntu20.04
  manylinux_2_31-arm64-ctk118:
    uses: rapidsai/shared-action-workflows/.github/workflows/docker-buildx-native-multiarch.yml@feat/docker-buildx-multiarch
    secrets: inherit
    with:
      push: true
      submodules: 'recursive'
      workdir: "./manylinux"
      docker-tag-multi: "rapidsai/manylinux_2_31:cuda-devel-11.8.0-ubuntu20.04"
      docker-tag-arm64: "rapidsai/manylinux_2_31:cuda-devel-11.8.0-ubuntu20.04-arm64"
      docker-build-arm64: "COMMIT_SHA=latest POLICY=manylinux_2_31 PLATFORM=aarch64 BASEIMAGE_OVERRIDE=nvidia/cuda:11.8.0-devel-ubuntu20.04 ./build.sh && docker tag quay.io/pypa/manylinux_2_31_aarch64 rapidsai/manylinux_2_31:cuda-devel-11.8.0-ubuntu20.04-arm64"
  manylinux_2_31-arm64-ctk120:
    uses: rapidsai/shared-action-workflows/.github/workflows/docker-buildx-native-multiarch.yml@feat/docker-buildx-multiarch
    secrets: inherit
    with:
      push: true
      submodules: 'recursive'
      workdir: "./manylinux"
      docker-tag-multi: "rapidsai/manylinux_2_31:cuda-devel-12.0.0-ubuntu20.04"
      docker-tag-arm64: "rapidsai/manylinux_2_31:cuda-devel-12.0.0-ubuntu20.04-arm64"
      docker-build-arm64: "COMMIT_SHA=latest POLICY=manylinux_2_31 PLATFORM=aarch64 BASEIMAGE_OVERRIDE=nvidia/cuda:12.0.0-devel-ubuntu20.04 ./build.sh && docker tag quay.io/pypa/manylinux_2_31_aarch64 rapidsai/manylinux_2_31:cuda-devel-12.0.0-ubuntu20.04-arm64"
