name: ci

on:
  pull_request:

jobs:
  build-cibuildwheel:
    uses: rapidsai/shared-action-workflows/.github/workflows/docker-buildx-native-multiarch.yml@feat/docker-buildx-multiarch
    secrets: inherit
    with:
      docker-tag-multi: "rapidsai/cibuildwheel:cuda-runtime-11.8.0-ubuntu20.04"
      docker-tag-amd64: "rapidsai/cibuildwheel:cuda-runtime-11.8.0-ubuntu20.04-amd64"
      docker-tag-arm64: "rapidsai/cibuildwheel:cuda-runtime-11.8.0-ubuntu20.04-arm64"
      push: true

      docker-build-cmd-amd64: "docker build -f cibuildwheel.Dockerfile --build-arg CPU_ARCH=amd64 --build-arg BASE_IMAGE=nvidia/cuda:11.8.0-runtime-ubuntu20.04 --build-arg CIBUILDWHEEL_VERSION=2.8.0 --pull . -t rapidsai/cibuildwheel:cuda-runtime-11.8.0-ubuntu20.04-amd64"

      docker-build-cmd-arm64: "docker build -f cibuildwheel.Dockerfile --build-arg CPU_ARCH=arm64 --build-arg BASE_IMAGE=nvidia/cuda:11.8.0-runtime-ubuntu20.04 --build-arg CIBUILDWHEEL_VERSION=2.8.0 --pull . -t rapidsai/cibuildwheel:cuda-runtime-11.8.0-ubuntu20.04-arm64"

  #build-citestwheel:
  #  uses: ./.github/workflows/build-and-publish-citestwheel.yml
  #  with:
  #    push: false
